### ISSUE TITLE
Validation is not performed when precision=0

### ISSUE THREAD

**Issue by fiducioso-elias** [IngressoRapidoWebComponents/money-input#2]
Thank you for creating the money-input component. We've used it on one of our prototypes pretty successfully. We noticed a few issues along the way. Here is the first one.

Validation is not performed if `precision=0`. `min-value` and `max-value` have no effect. The component never turns "red" when an invalid value is entered. As in:

``` html
<money-input id="salary" required precision="0" label="What is your salary?" value="{{salary}}" min-value="0" max-value="10000000"></money-input>
```

We worked around the issue by calling the `validate()` every time `value` changes, but that is less than ideal. 

Inserting `this.validate();` before line 219 in money-input.html seems to address the issue.

**Comment by gabycperezdias** [comment]
Hi, sorry for the delay... I will work on this problem, I will notice you as soon as we release a new version :)

Just to check, what are the other issues?

**Comment by fiducioso-elias** [comment]
Thank you for looking into this. About the other problems... There was definitely one more. I should probably open a separate issue for it when I gather my thoughts. In a nutshell, I expected the "value" property to notify when user erases the last digit of the input. By "notify" I mean change the value of the variable the property is bound to; and trigger observers on the variable. All that happens whenever I add or change a digit, but not when I erase the last digit. The "value" property of the "standard" paper-input component does notify when the last character is erased as far as I can tell.

**Comment by gabycperezdias** [comment]
Hi, about the main issue I will have a new version with the fix today or tomorrow... about the above mentioned problem, I will check... Thanks for the feedback :)

**Comment by gabycperezdias** [comment]
Hey, there's a new version with the fix so I will close this issue... if the problem persists just let me know.... and about the other issue I don't know if I understood correctly since the tests I did covered the scenario you have mentioned :/
