### ISSUE TITLE
Hide the Floating Label

### ISSUE THREAD

**Issue by samcarecho** [IngressoRapidoWebComponents/money-input#4]
money-input does not allow to pass to paper-input the noLabelFloat property.

Solution:
- add a new Boolean property called "noLabelFLoat"
- add a new attribute to paper-input called no-label-float to take the value of the new property "noLabelFloat"

**Comment by gabrielle-perez-movile** [comment]
@samcarecho There was a merge regarding this problem. It solved your problem?
